### PR TITLE
Super hacky implementation on current webgpu prototype

### PR DESCRIPTION
**Pull request by kainino0x**
This is super hacked and you will need to do some build/test system finagling to make this make sense.

You should be able to run this with [this build](https://drive.google.com/open?id=1QxI0DKjE9jBlOfo5Dlhk7XhAi2Icf2bW).

by running it as `./Chromium.app/Contents/MacOS/Chromium --enable-unsafe-webgpu`

---
This change is [Reviewable](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1)

### CODE REVIEW

**Comment by kainino0x** [comment]
(Mac only, btw)

**Review by dsmilkov — COMMENTED** [review]
Thanks Kai. This is exciting. LGTM on my side. Just left a few comments

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-:-Lb8ou8m1THRPxqgMS49:bcimmco)* status: all files reviewed, 4 unresolved discussions (waiting on @kainino0x)

___
*[src/index.ts, line 12 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8o0oh0IYnhGT6ybpf:-Lb8o0oh0IYnhGT6ybpg:b9ugc5b) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/index.ts#L12)):*
> ```XML
>   const adapter = await navigator.gpu.requestAdapter({});
>   const device = await adapter.requestDevice({});
>   const shaderc = await Shaderc;
> ```

is there a reason you don't wait to push these into the constructor of WebGPUBackend?
___
*[src/mul_test.ts, line 6 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8oFnH5K8MXD__hBIB:-Lb8oFnH5K8MXD__hBIC:bog2f55) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/mul_test.ts#L6)):*
> ```XML
> describe("WebGPU backend", () => {
>   it("A * B elementwise", async () => {
>     await tf.ready;
> ```

interesting. Is there a way to avoid the await ready  in the future?
___
*[src/shaderc/index.js, line 1 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8oOUM0x11r8ZHy4rr:-Lb8oOUM0x11r8ZHy4rs:b-vn6ywl) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/shaderc/index.js#L1)):*
> ```JavaScript
> let Shaderc;
> ```

this is auto-generated right? Few q:
- Is the C++ code behind the wasm binary open-sourced?
- If yes, can you add instructions in the readme on how to regenerated this.
- How often does the C++ code change?
___
*[src/shaderc/shaderc.wasm, line 0 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8mgIfB5OaxzsFDO11:-Lb8mgIfB5OaxzsFDO12:bbx2mzf) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/shaderc/shaderc.wasm#L0)):*
Curious, will we need this glsl to spearV wasm compiler in the long term, or is this a short-term solution?

**Review by Kangz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1)* status: all files reviewed, 4 unresolved discussions (waiting on @dsmilkov and @kainino0x)

___
*[src/mul_test.ts, line 6 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8oFnH5K8MXD__hBIB:-Lb8pTZ-1cxG05AsVqqT:bdxrxch) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/mul_test.ts#L6)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

interesting. Is there a way to avoid the await ready  in the future?
</blockquote></details>

WebGPU device creation is asynchronous because it can > 100ms to happen. Maybe we can put the asynchrony some other place but if I understand JS correctly, it will have to appear somewhere.
___
*[src/shaderc/index.js, line 1 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8oOUM0x11r8ZHy4rr:-Lb8pliOAB161oRU4NtT:b-8kp97) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/shaderc/index.js#L1)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

this is auto-generated right? Few q:
- Is the C++ code behind the wasm binary open-sourced?
- If yes, can you add instructions in the readme on how to regenerated this.
- How often does the C++ code change?
</blockquote></details>

It is autogenerated.

This is a very old (EOY 2017?) version of shaderc which is open-source [here](https://github.com/google/shaderc). The idea is that the WebGPU group would provide the basis of the ecosystem with toolchains like this (and a nicer looking JS API). The C++ code changes very often but if a compiled shader works with a specific version of the compiler on a browser, it should work on all of them (although in the short term there will be some breakage as we add validation rules).
___
*[src/shaderc/shaderc.wasm, line  at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8mgIfB5OaxzsFDO11:-Lb8qkNACGJKQt1qEDIW:bthvqac) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/shaderc/shaderc.wasm#L)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Curious, will we need this glsl to spearV wasm compiler in the long term, or is this a short-term solution?
</blockquote></details>

The shading language discussions are still a hot topic in the group. If SPIR-V is chosen (which we hope) there will be several choices, one of which is that shaders are compiled offline to SPIR-V and only specialized at run-time. Or they are compiled like they are in this PR (we could have CDN version of compilers for code caching etc). Also we want to provide smaller compiler binaries, 500kb might be too much for some folks.

**Review by kainino0x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1)* status: all files reviewed, 4 unresolved discussions (waiting on @dsmilkov and @Kangz)

___
*[src/index.ts, line 12 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8o0oh0IYnhGT6ybpf:-Lb9ZJgP7k3hFfvjHug7:b-brgbje) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/index.ts#L12)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

is there a reason you don't wait to push these into the constructor of WebGPUBackend?
</blockquote></details>

Only because they are async and I needed them to be ready before the backend does stuff. Please feel free to restructure, I don't really understand what is the right way to do things.
___
*[src/mul_test.ts, line 6 at r1](https://reviewable.io/reviews/annxingyuan/tfjs-webgpu/1#-Lb8oFnH5K8MXD__hBIB:-Lb9ZZPGBR0bFQj2qBrx:b-nt9x60) ([raw file](https://github.com/annxingyuan/tfjs-webgpu/blob/a5fa1ce67339c0c904d57253dd0b3885e3fd58e3/src/mul_test.ts#L6)):*
<details><summary><i>Previously, Kangz (Corentin Wallez) wrote…</i></summary><blockquote>

WebGPU device creation is asynchronous because it can > 100ms to happen. Maybe we can put the asynchrony some other place but if I understand JS correctly, it will have to appear somewhere.
</blockquote></details>

Yes, it'll have to be somewhere. It can be inside the backend if there's some async point where it can wait, or if the backend queues up work to be submitted when the device is ready.

**Pull request merged**
